### ISSUE TITLE
Force color output does nothing (minimal)

### ISSUE THREAD

**Issue by webdevnerdstuff** [AlexFalappa/nb-springboot#105]
Ubuntu 16.04
Netbeans v8.2

In Netbeans Options, if the "Force color output" is checked, it does not color the output.

If I add "spring.output.ansi.enabled=always" into the configuration property it still doesn't really colorize the output. Basically the only thing that changes is ":: Spring Boot ::" color changes, but nothing else. I have also tried adding the variable "SPRING_OUTPUT_ANSI_ENABLED", and the same result happens.

No matter what I do, it just does not really colorize the output, unless I'm misunderstanding how the color output works. My goal is to have the output like how it is in Eclipse. I have tried under multiple Appearances as well, and nothing works.

Before:
![screenshot](https://user-images.githubusercontent.com/14927668/31194321-a56653b8-a8fb-11e7-8104-eff9d7afa899.png)

After:
![screenshot-2](https://user-images.githubusercontent.com/14927668/31194818-26a254bc-a8fd-11e7-8802-d5750b79605a.jpg)

**Comment by webdevnerdstuff** [comment]
Never mind. It was a problem with the VM Arugments and Program Arguments.

**Comment by AlexFalappa** [comment]
Glad you were able to resolve it!
