### ISSUE TITLE
Manual restart broken with Spring Boot 2.0.x

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#107]
It seems that due to stricter relaxed binding rules in Spring Boot 2.0.x `SPRING_DEVTOOLS_RESTART_TRIGGER_FILE` environment variable is no more mapped to `spring.devtools.restart.trigger-file` configuration property.

The recognized form is `SPRING_DEVTOOLS_RESTART_TRIGGERFILE`.

This new form is not valid for Spring Boot 1.5.x.

Try to switch between the two forms when creating new projects and reacting to user edits of boot version directly in the `pom.xml`

**Comment by snicoll** [comment]
@AlexFalappa We've just fixed something in the snapshot so that the old property also works but we don't want to advertize that too much.

Is there a way you can change the property according to the running Spring Boot versions?

**Comment by AlexFalappa** [comment]
@snicoll dealing with this when creating new projects is easy while managing the user changing the boot version in the `pom.xml` harder.

Will try my best.

**Comment by AlexFalappa** [comment]
A very simple solution could be to define both forms.

**Comment by snicoll** [comment]
I am not sure i like this idea. If we ever turn validation on for this namespace it will cause startup failure.

**Comment by AlexFalappa** [comment]
@snicoll you mean it will cause a property name clash in one of the boot versions?

**Comment by snicoll** [comment]
No. The new name will not bind anything with 1.5.x. Regardless I don't like the approach of specifying the same thing twice. 

I'd go with the current format if you can't detect the version of Spring Boot.

**Comment by AlexFalappa** [comment]
@snicoll I agree specifying both environment variables is very very hacky .
Let me have a look at it.
