### ISSUE TITLE
spring.jackson.serialization.write-null-map-values=false

### ISSUE THREAD

**Issue by zhanhb** [AlexFalappa/nb-springboot#108]
Cannot parse 'write-null-map-values' as com.fasterxml.jackson.databind.SerializationFeature

**Comment by AlexFalappa** [comment]
Note to self: in this case `write-null-map-values` should be a relaxed binding to `SerializationFeature.WRITE_NULL_MAP_VALUES`.
Thorough support of configuration properties of type `Map<K,V>` is required to handle this.

**Comment by snicoll** [comment]
@AlexFalappa indeed, please check [this section on the wiki](https://github.com/spring-projects/spring-boot/wiki/IDE-binding-features#enum) for more details.
