### ISSUE TITLE
Improve Spring Initializr project wizard

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#117]
The new _Spring Initializr_ project wizard could see some improvements:
* In the _Base Properties_ step
    * edits to the `Artifact` field could be propagated to the `Name` field (but not viceversa)
    * edits to the `Group` and `Artifact` fields could be concatenated and propagated to the `Package Name` field 
    * If the user afterwards edits the `Package Name` or `Name` the link should be interrupted
    * preselect the fields content when tabbing between textfields
* In the _Dependencies_ step
    * Remember and present a small set (3 to 5) of frequently used dependencies
    * ~~Preselect `Configuration Processor` dependency~~

**Comment by snicoll** [comment]
> Preselect Configuration Processor dependency

Why? That's only necessary if you are crafting your own `@ConfigurationProperties` so I see no reason to make that mandatory.

**Comment by AlexFalappa** [comment]
Point taken
