### ISSUE TITLE
Spring Boot Restart Button

### ISSUE THREAD

**Issue by xyraclius** [AlexFalappa/nb-springboot#128]
Hey Bro, what's function of Spring Boot Restart Button at toolbar?
i've tried but it showing message: Project [Project Name] Application Restart disabled or not applicable!

![nbsb](https://user-images.githubusercontent.com/3437414/35037975-b80fa570-fbab-11e7-9ad4-6de85094cdcd.jpg)

**Comment by AlexFalappa** [comment]
You should have a dependency on spring-boot-devtools in your pom, then start the project, if you have checked the manual restart option in the project properties then you can trigger an application restart clicking that button.
The documentation is in the wiki: https://github.com/AlexFalappa/nb-springboot/wiki/Devtools-Manual-Restart
Also see the DevTools section in Spring  Boot reference.
