### ISSUE TITLE
BasicSpringbootProject wizard creates nbactions_1.xml

### ISSUE THREAD

**Issue by Chris2011** [AlexFalappa/nb-springboot#129]
The project wizard for `Spring Boot basic project` will create nbactions.xml and nbactions_1.xml.

Here you can see the differences: https://pastebin.com/GE5Ay9Hd (nbactions.xml)
and: https://pastebin.com/Nu0xiTfK (nbactions_1.xml)

This shouldn't happen.

Cheers

Chris

**Comment by AlexFalappa** [comment]
Not reproducible on master.
May have been fixed by other reworkings.

**Comment by Chris2011** [comment]
But I use the latest verson 1.6.1. So there is no newer version, right? And 1.6.1 should be from master if you are working correctly with the branches.

**Comment by AlexFalappa** [comment]
`master` is the head of development, will become next version.
