### ISSUE TITLE
Code templates?

### ISSUE THREAD

**Issue by markiewb** [AlexFalappa/nb-springboot#13]
You could also provide code templates and bundle it using your plugin.

See 
https://github.com/markiewb/eclipsecodeformatter_for_netbeans/commit/f018cfc8b36adccf19240125e87b49056d6a64d3

The NetBeans dev FAQ is currently not editable, else I would have documented it already.

**Comment by AlexFalappa** [comment]
Could you make an example please?
The plugin already contains some file templates and I am thinking to add some Spring file templates too (see issue #6).

**Comment by markiewb** [comment]
I got it. Code generators is the proposed way of working with this plugin.  

I thought originally that you could provide code templates for within pom files to add dependencies.  I use code generators seldom. Closing this issue
