### ISSUE TITLE
Disables context menu shortcuts

### ISSUE THREAD

**Issue by ginalpisti** [AlexFalappa/nb-springboot#140]
Installing this plugin made the context menu button not work in the projects tab. Neither would the alternative (Shift+F10) work. Disabling or uninstalling the plugin solves the shortcut problem.

I use NetBeans 8.2 on an up-to-date Windows 10 laptop, default keymapping, clean install with the default plugins for Java EE version ([NetBeans 8.2 for Java EE](http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-javaee-windows.exe)). The only extra plugin is NB SpringBoot downloaded through the NetBeans plugin manager from the plugin portal.

**Comment by AlexFalappa** [comment]
Already reported in #127  and #106 .
Fixed in master, will be released soon as v2.0.1

**Comment by AlexFalappa** [comment]
Unfortunately this won't be fixed yet, the fix has huge side effects on configuration properties completion
