### ISSUE TITLE
Support for Netbeans 10

### ISSUE THREAD

**Issue by jonybuzz** [AlexFalappa/nb-springboot#143]
It would be nice to use this plugin in the recent stable version of Apache Netbeans 10.0 with Java 11 support

**Comment by AlexFalappa** [comment]
@jonybuzz the latest version of NB SpringBoot works perfectly on NetBeans 10 running on JDK11 (I have tried it myself).

The plugin however is not available in the UpdateCenter as the plugin portal (and more importantly the verification process) are currently a bit of a mess awaiting transition to the Apache Foundation.

Install manually downloading the `nbm` file from the [Releases page](https://github.com/AlexFalappa/nb-springboot/releases).

**Comment by mtbadi39** [comment]
Hi @jonybuzz ,@AlexFalappa
I can confirme that it works also with Windows 10 64-btis, OpenJDK 11.01 64-btis, Apache Netbeans 10, Spring Boot 2.1.2.RELEASE, see [139#](https://github.com/AlexFalappa/nb-springboot/issues/139#issuecomment-432295320)
