### ISSUE TITLE
Better proposal in file templates

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#15]
Current class templates, such as CommandLineRunner, fill in the class name starting with a lowercase character, such as `newCommandLineRunner`.

Class name proposal should start with an uppercase character as in `NewCommandLineRunner`.

Hint seen on http://info.michael-simons.eu/2016/06/19/netbeans-ide-plugin-supporting-programming-with-spring-boot/

**Comment by michael-simons** [comment]
Thanks Alex! I'd read through the sources, but as much as I use NetBeans as an IDE, I never used it as platform or written plugins for it, so sadly I couldn't improve it myself quickly.
