### ISSUE TITLE
Allow trigger file for reload

### ISSUE THREAD

**Issue by everflux** [AlexFalappa/nb-springboot#19]
Great plugin, works like a charm. It would be nice to be able to have more control over the reload when using devtools: Currently when using compile-on-save and devtool, each save in NB results in an application reload.
It would be nice if there is an option (f.e. toolbar icon) to trigger the reload using a trigger file. See http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart-triggerfile

**Comment by AlexFalappa** [comment]
This is definitely an interesting suggestion.
I should experiment a bit more with the trigger file mechanism and design a good integration.
Adding to the roadmap.
