### ISSUE TITLE
ConfigurationProperties file template doesn't work out of the box

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#27]
The `ConfigurationProperties` file template should produce a class that is annotated with `@Component` besides `@ConfigurationProperties` to make it discoverable by Spring automatic scanning

**Comment by snicoll** [comment]
@AlexFalappa I wouldn't do that. `ConfigurationProperties` should remain simple pojo. In particular, if you start injecting other dependencies to it, that might be a smell it's no longer "configuration".

That's  why `@EnableConfigurationProperties(Abc.class)` exists in the first place. I'd find it much better if the template did not add a `@Component` to the class.

**Comment by AlexFalappa** [comment]
@snicoll thanks for your insightful comment.

Actually I was mimicking the [examples in the documentation](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties) which mostly show classes annotated with `@Component`.

At a deeper examination the documentation also suggest the use of the `@EnableConfigurationProperties` annotation with explicit delaration of configuration properties classes, an approach that I haven't followed before and that I must try for sure.

I'm closing this issue: the programmer will decide which approach suits best to him and add the `@Component` annotation if he wishes.

**Comment by snicoll** [comment]
@AlexFalappa thank you for the reminder! I've polished that part of the doc in https://github.com/spring-projects/spring-boot/commit/d5441d27f6d841a1b241b4f08e3aae90587ef65d
