### ISSUE TITLE
Show request mappings of MVC beans

### ISSUE THREAD

**Issue by michael-simons** [AlexFalappa/nb-springboot#35]
Hello Alessandro,

one nice feature to have would be a view that shows the `@RequestMapping` of recognized beans like this:

https://twitter.com/rotnroll666/status/753136922927718400/photo/1

I'm only a NetBeans user, don't have much experience writing my own plugins, but maybe I could help on the Spring site? 

Thanks,
Michael

**Comment by AlexFalappa** [comment]
Closed by PR #36

**Comment by michael-simons** [comment]
Just to let you know: Colleague and I are using the beta since last weeks. Didn't find any problems so far.

**Comment by AlexFalappa** [comment]
Glad to hear it!

I've found a strange behaviour on `@Controller` annotated classes. Will open a separate issue for it, I would appreciate your opinion on it.

**Comment by AlexFalappa** [comment]
Nevermind, I had wrong assumptions on how it should be working.

**Comment by michael-simons** [comment]
Maybe your assumptions are better than mine? :) I'm open for suggestions any time!

**Comment by AlexFalappa** [comment]
I noticed that if I have:
``` java
@Controller
public class NewController {
    @RequestMapping("/url")
    public String page(Model model) {
        return "view.name";
    }
}
```
the request mapping view shows no HTTP method. I assumed a default of `GET` but after looking at the documentation I realized that the default is all methods. I think I will mention it in the wiki when documenting this new functionality.

**Comment by michael-simons** [comment]
Exactly, the method acts as a restriction.

If you at `@RequestMapping(method = GET)` at controller level and omit it on method level like in your example, then it means only GET there, too.
