### ISSUE TITLE
Reload trigger action funcionality requires restart of NetBeans after installation 

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#38]
If NetBeans is not restarted several NullPointerException are thrown in `GlobalActionContextProxy#clearProjectLookup()` and `GlobalActionContextProxy#updateProjectLookup()` methods.

This happens because the `GlobalActionContextProxy#createGlobalContext()` is called only during NetBeans startup phase.

**Comment by michael-simons** [comment]
Hi.
I've startet a NetBeans 8.1 download with a fresh user dir (`./bin/netbeans --userdir ~/tmp/foobar`), installed the beta (accept license, unsigned ok) and then the new navigator was there and working after project scanning finished.
Uninstalling however did require a restart (but if I remember correctly, it did before as well)

**Comment by AlexFalappa** [comment]
@michael-simons the need to restart seems unrelated to the  request mapping navigator panel, it is instead caused by the devtools reload trigger internals.

To better support enabling the reload action I had to override how NetBeans "remembers" the last selected project in the project tab.

I'm changing the bug description to better highlight this.
