### ISSUE TITLE
Improve request mapping navigator panel

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#41]
The navigator panel table could see some improvements:

- [X] Use an `ETable` from `swing.outline` module. This should bring sorting, column auto resize and visibility toggle.
- [x] Consider not to show the package when the types are different (i.e. `method(String, Integer)` instead of `method(java.lang.String, java.lang.Integer)` but `method(java.util.Timestamp, java.sql.Timestamp)`
- [x] Add custom cell renderers to bring some color

**Comment by michael-simons** [comment]
Coworker of mine recommend ETable or something that uses nodes as well… JTable was easier for me, sorry… I have Swing experience, but not NetBeans internal experience.

Colors are certainly doable!
