### ISSUE TITLE
Respect project license

### ISSUE THREAD

**Issue by michael-simons** [AlexFalappa/nb-springboot#42]
When using the templates for repositories, controllers and other stereotypes, I expect them to respect the license configured under project settings.

This only works if I select one of the "Build in" global licenses, but not if I check "Use project location".

**Comment by AlexFalappa** [comment]
As a workaround you can edit the desired template (choose *Tools* -> *Templates*, then select the *Spring Boot* or *Spring Framework* group) and replace this line:
```
<#include "../Licenses/license-${project.license}.txt">
```
with:
```
<#include "${project.licensePath}">
```
