### ISSUE TITLE
Custom project icon 

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#47]
Different icon for spring boot maven projects in the project view

**Comment by Chris2011** [comment]
Yes, that would be cool :) Shouldn't be that hard to realize. You can set the project icon and merge them with the spring icon to the top like he is doing this for a PHP project with WordPress support: https://github.com/junichi11/netbeans-wordpress-plugin/blob/bdde354770a8e20d8613812967e2b2e4d1ee1556/src/org/netbeans/modules/php/wordpress/ui/logicalview/MVCNode.java#L100

smth like this :)

**Comment by AlexFalappa** [comment]
@Chris2011 are you sure this does not imply loosing the existing maven project _nature_?
In the NetBeans platform documentation it is explained how to create a new project type from scratch not how to extend existing ones.

**Comment by Chris2011** [comment]
Good question, take a look into the MVCNode.java file from the WordPress plugin, he does more than only merging the images.
