### ISSUE TITLE
Add support for new dependencies "_links"

### ISSUE THREAD

**Issue by snicoll** [AlexFalappa/nb-springboot#71]
Spring Initializr can now expose "links" for each dependency (see https://github.com/spring-io/initializr/pull/279). We primarily use this to add reference to a guide or a section of the developer guide. That information is exposed in the metadata using a new "_links" element (HAL compliant).

More specific information about IDE dev can be found [on the wiki](https://github.com/spring-io/initializr/wiki/Dependency-links-usage-in-clients)

It would be nice if you'd use that information in one way or another.

**Comment by AlexFalappa** [comment]
I'm unsure about how to use these new metadata in the *Spring Boot Initializr* project wizard.
Current ideas:

- an icon near the dependency selection checkboxes showing the first link
- a new summary step at the end of the wizard showing reference and guides links for all selected dependencies
- hyperlink as dependency checkbox text

It seems that, anyway, links to reference docs and guides for selected dependencies will be included in a markdown document at the root of the project, see [this issue](https://github.com/spring-io/initializr/issues/353).

**Comment by snicoll** [comment]
Yes but I think IDE have more space and are more "wizard style": it would be a nice way to discover that certain dependencies have a guide or a doc section before creating the project itself.
