### ISSUE TITLE
"Add Spring Boot starter" as a maven pom.xml code generator

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#73]
It would be useful to get assistance in adding Spring Boot managed dependencies in `pom.xml`s of existing projects.

The starter's maven coordinates and other metadata (BOMs and extra repositories) are exposed by the *Spring Initializr* web service in a currently undocumented endpoint: `https://start.spring.io/dependencies{?bootVersion}`

**Comment by snicoll** [comment]
See https://github.com/spring-io/initializr/issues/371
