### ISSUE TITLE
Missing license text, when installing from built-in plugin center

### ISSUE THREAD

**Issue by markiewb** [AlexFalappa/nb-springboot#79]
![2017-04-23_12h16_30](https://cloud.githubusercontent.com/assets/1857095/25312641/e50fe334-281e-11e7-9086-83930e816fd6.png)

**Comment by AlexFalappa** [comment]
The license should be correctly set in the project, it also happened in the past. 
Let's hope a rebuild will fix it.

**Comment by AlexFalappa** [comment]
As of today (May 15 2017) the plugin is available from the Update Center for NB 8.2, verified that the license is correctly shown during installation.
