### ISSUE TITLE
Chopping when completing configuration property value

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#82]
When completing the following input:
```
spring.jpa.hibernate.ddl-auto=n|
```
after completing the proposed `none` value you obtain:
```
sprinone
```

**Comment by AlexFalappa** [comment]
Fixed in 48160cbaebe9c59b8cf17426a40958e41d7fb456

**Comment by michael-simons** [comment]
Hah! Good one. Thanks!
