### ISSUE TITLE
Support for deprecation level 

### ISSUE THREAD

**Issue by snicoll** [AlexFalappa/nb-springboot#84]
Spring Boot has introduced a new property in the `deprecation` object called `level`. 

What is expected from the IDE is [documented here](https://github.com/spring-projects/spring-boot/wiki/IDE-binding-features#deprecation)

We intend to insert a bunch of such `error` properties for the things that we are breaking in Spring Boot 2 so it would be good if NetBeans could show them as an error.

While the code has been added to Spring Boot 2, the annotation processor doesn't do anything with this as "error" properties are always defined in manual meta-data so please do not constraint its use to Spring Boot 2 only.

**Comment by AlexFalappa** [comment]
Sensible support to this new Spring Boot feature may be split into:
1. Do not show or mark deprecated configuration properties with level _error_ in completion list
2. Highlight and mark lines with _error_ level deprecated properties in editor gutter
3. Offer an editor hint to delete the highlighted line or substitute the configuration property name with its replacement (if available)

Item 1 is more readily feasible while items 2 and 3 depend on other improvements to the configuration editor.

**Comment by AlexFalappa** [comment]
Implemented in 3c04602812b93fdea1ee05a9fc36c7159d5fb843

**Comment by AlexFalappa** [comment]
Please note that at the moment a bug in the `spring-configuration-processor` ([#9449](https://github.com/spring-projects/spring-boot/issues/9449)) prevents the use of deprecation level in user defined properties
