### ISSUE TITLE
Upgrade to Spring Boot 1.5.4

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#85]
Use Spring Boot v1.5.4 as internal dependency.

This should allow to support recent addition to deprecation attributes in configuration properties metadata (see #84)

**Comment by snicoll** [comment]
Sounds like a bold move to me. You don't need any of the 2.0 bits to support #84 (it really is a new property only and the annotation processor will not generate it since there won't be code to support a property that has actually been removed).

Am I missing something?

**Comment by AlexFalappa** [comment]
@snicoll at the moment the plugin code base depends on the `spring-boot-configuration-processor` maven module, more specifically re-uses classes in the `org.springframework.boot.configurationprocessor.metadata` package for the configuration data object model and to perform unmarshalling of the json storage format.

This is a _technical debt_ inherited from the original NB plugin from @keevosh.

Now I see that in [your spring boot commit](https://github.com/spring-projects/spring-boot/commit/527c2e7b75a9db34290ff4c1582ef6c9fa68af5b) you added the deprecation level to the source of the `spring-boot-configuration-metadata` maven module instead (`Deprecation` class).

What should I do? Am I using the wrong module?
What are the differences between the `spring-boot-configuration-processor` and `spring-boot-configuration-metadata` modules?

**Comment by snicoll** [comment]
@AlexFalappa I wasn't aware that you were relying on that. That is fine, this module is also used by STS but they usually copy the code over so that the integration does not depend on Spring Boot itself.

I've just backported that change to `1.5.x` so you'll have it as of `1.5.4`. You really shouldn't upgrade to Spring Boot 2 for that reason as I'd like to get this support ASAP (i.e. before Spring Boot 2 goes GA).

**Comment by AlexFalappa** [comment]
@snicoll updated issue title accordingly.

Do you happen to know which module does STS use, spring-boot-configuration-**processor** or spring-boot-configuration-**metadata** ?

**Comment by snicoll** [comment]
The one we're discussing here. Metadata. You shouldn't be using the processor api yourself.

**Comment by AlexFalappa** [comment]
@snicoll thanks for the clarification.

Unfortunately the original NB plugin used the processor API.

I am opening another issue for that move.
