### ISSUE TITLE
Described "Requirements and Installation" appear to be inaccurate

### ISSUE THREAD

**Issue by DevSidious** [AlexFalappa/nb-springboot#87]
> This plugin requires NetBeans 8.1 or above running on JDK 7 or above.

Ok.

**Tested with NetBeans 8.2 (SE, EE distributions updated after installation) and Oracle JDK 1.8.0_131:**

> The plugin is available in the Plugin Portal Update Center thus it can be downloaded and installed trough Tools > Plugins > Available Plugins.

No, it is not.

> Alternatively download the desired nbm package from https://github.com/AlexFalappa/nb-springboot/releases , go to Tools > Plugins > Downloaded and click on Add Plugins... button. Choose the downloaded nbm package file then click Install.

Manual install fails with:

Some plugins require plugin Classpath APIs to be installed.
The plugin Classpath APIs is requested in version >= 1.50.1 but only 1.42.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Progress API to be installed.
The plugin Progress API is requested in version >= 1.46.1 but only 1.38.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin org.netbeans.api.templates to be installed.
The plugin org.netbeans.api.templates is requested in version 1.6.1.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin MultiView Windows to be installed.
The plugin MultiView Windows is requested in version >= 1.43.1 but only 1.40.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Javac API Wrapper to be installed.
The plugin Javac API Wrapper is requested in version >= 8.13.1.3 but only 8.11.1.3 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin JSON Simple Library to be installed.
The plugin JSON Simple Library is requested in version >= 0.11.1 but only 0.9.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Common Scripting Language API (new) to be installed.
The plugin Common Scripting Language API (new) is requested in version >= 2.51.1.2.1.1.8.1 but only 2.47.1.2.1.1.8 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Editor Code Completion to be installed.
The plugin Editor Code Completion is requested in version >= 1.43.1.2 but only 1.40.1.2 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Editor Error Stripe Impl to be installed.
The plugin Editor Error Stripe Impl is requested in version >= 2.33.1.1.1 but only 2.30.1.1.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Editor Library 2 to be installed.
The plugin Editor Library 2 is requested in version >= 2.4.1.44.1 but only 1.85.1.43 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin org.netbeans.modules.java.project.ui to be installed.
The plugin org.netbeans.modules.java.project.ui is requested in version 1.66.1.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Java Source to be installed.
The plugin Java Source is requested in version >= 0.149.1.32.2.25.2.1 but only 0.138.3.32.2.25.8 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin org.netbeans.modules.java.source.base to be installed.
The plugin org.netbeans.modules.java.source.base is requested in version 2.9.1.2.2.25.8.1.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Java Source UI to be installed.
The plugin Java Source UI is requested in version >= 1.42.1.1.25.32.2 but only 1.38.3.1.32 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Lexer to be installed.
The plugin Lexer is requested in version >= 1.62.1.1 but only 1.59.1.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Maven Embedder to be installed.
The plugin Maven Embedder is requested in version >= 2.51.1 but only 2.46.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Maven Editor Model to be installed.
The plugin Maven Editor Model is requested in version >= 1.41.1 but only 1.38.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Maven Projects to be installed.
The plugin Maven Projects is requested in version >= 2.118.1 but only 2.107.5 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Options Dialog and SPI to be installed.
The plugin Options Dialog and SPI is requested in version >= 1.44.1 but only 1.41.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Project API to be installed.
The plugin Project API is requested in version >= 1.65.1 but only 1.60.2 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin org.netbeans.modules.projectuiapi.base to be installed.
The plugin org.netbeans.modules.projectuiapi.base is requested in version 1.83.1.9.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Project UI API to be installed.
The plugin Project UI API is requested in version >= 1.86.1.8 but only 1.81.1.8 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Extensible Abstract Model (XAM) to be installed.
The plugin Extensible Abstract Model (XAM) is requested in version >= 1.31.1.1 but only 1.28.1.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Navigator API to be installed.
The plugin Navigator API is requested in version >= 1.36.1 but only 1.33.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin ETable and Outline to be installed.
The plugin ETable and Outline is requested in version >= 1.32.1 but only 1.30.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin UI Utilities API to be installed.
The plugin UI Utilities API is requested in version >= 7.65.1 but only 7.62.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Dialogs API to be installed.
The plugin Dialogs API is requested in version >= 7.41.1 but only 7.38.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Explorer & Property Sheet API to be installed.
The plugin Explorer & Property Sheet API is requested in version >= 6.61.1 but only 6.57.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin File System API to be installed.
The plugin File System API is requested in version >= 9.8.1 but only 8.12.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Datasystems API to be installed.
The plugin Datasystems API is requested in version >= 7.63.1 but only 7.57.2 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Module System API to be installed.
The plugin Module System API is requested in version >= 7.47.1 but only 7.43.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Nodes API to be installed.
The plugin Nodes API is requested in version >= 7.42.1 but only 7.39.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Text API to be installed.
The plugin Text API is requested in version >= 6.66.1 but only 6.62.2 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Utilities API to be installed.
The plugin Utilities API is requested in version >= 9.5.1 but only 8.39.1 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Lookup API to be installed.
The plugin Lookup API is requested in version >= 8.32.1 but only 8.25.2 was found.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin org.openide.util.ui to be installed.
The plugin org.openide.util.ui is requested in version 9.4.1.  The following plugin is affected:       NB SpringBoot 
Some plugins require plugin Window System API to be installed.
The plugin Window System API is requested in version >= 6.74.1 but only 6.71.1 was found.  The following plugin is affected:       NB SpringBoot  Some plugins not installed to avoid potential installation problems.

I only managed to manually install the plugin in Netbeans nightly builds:
http://bits.netbeans.org/download/trunk/nightly/latest/

**Comment by AlexFalappa** [comment]
@DevSidious as of today (May 15 2017) the NB Spring Boot plugin has been verified by the folks at the NetBeans plugin portal and thus is available from the Update Center (Tools > Plugins) for NetBeans 8.2 only, it's not available for NetBeans 8.1 yet.

I will add some statements to the documentation explaining the NetBeans plugins verification process and a notice about delayed availability of new releases on the Update Center.

I could not reproduce your manual installation issues, I have successfully installed v1.5.1 on _NetBeans 8.2 with Oracle JDK 1.8.0_131_ and _NetBeans 8.1 with Oracle JDK 1.7.0_80_.

**Comment by DevSidious** [comment]
Mistery solved.  I was landing on the download page from a google "download netbeans" result page and that caches the old NetBeans 8.0, 8.0.1 & 8.0.2 download links, instead of 8.2.

I can confirm that the plugin is available and behaves as expected in NetBeans 8.2. My apologies.

Thank you for the prompt intervention and for publishing this awesome plugin. Much appreciated. :)

**Comment by mtbadi39** [comment]
@DevSidious @AlexFalappa 
The plugin is not get listed in the Available Plugins in Netbaens 8.2, Why ?
Just for info, manual download and install works fine.

**Comment by snicoll** [comment]
Because https://github.com/AlexFalappa/nb-springboot/issues/136#issuecomment-375203274

**Comment by mtbadi39** [comment]
Sorry !

> and thus is available from the Update Center (Tools > Plugins) for NetBeans 8.2 only, it's not available for NetBeans 8.1 yet.

in the [comment](https://github.com/AlexFalappa/nb-springboot/issues/87#issuecomment-301411587) above confused me.
