### ISSUE TITLE
Suggestion: Use new annotations in RestController template

### ISSUE THREAD

**Issue by rafaeldev** [AlexFalappa/nb-springboot#95]
If the project is using Spring Boot version 1.4.x or above the Rest Controller template could use the new `@<verb>Mapping` annotations as follows:
```
@RestController
@RequestMapping("/url")
public class ${name} {

    @GetMapping
    public List<Object> list() {
        return null;
    }

    @GetMapping("/{id}")
    public Object get(@PathVariable String id) {
        return null;
    }

    @PutMapping("/{id}")
    public ResponseEntity<?> put(@PathVariable String id, @RequestBody Object input) {
        return null;
    }

    @PostMapping("/{id}")
    public ResponseEntity<?> post(@PathVariable String id, @RequestBody Object input) {
        return null;
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Object> delete(@PathVariable String id) {
        return null;
    }

}
```

**Comment by AlexFalappa** [comment]
@rafaeldev at first I also using the new specialized `@<verb>Mapping` annotations would be cool, then I realized that I would loose compatibility with older boot versions (namely 1.3.x and below).

Consider that as of this writing is still possible to choose Boot version 1.3.8 on the _Spring Initializr_.

A more sensible solution would be to use the new annotations on Boot versions 1.4.x and above.

I am changing the issue in that direction

**Comment by AlexFalappa** [comment]
Minimum Boot version on *Spring Initializr* service is now **1.4.7** thus now this could be taken into consideration.
